// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AlarmMessage.proto

#ifndef PROTOBUF_INCLUDED_AlarmMessage_2eproto
#define PROTOBUF_INCLUDED_AlarmMessage_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_AlarmMessage_2eproto 

namespace protobuf_AlarmMessage_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_AlarmMessage_2eproto
class AlarmMessage;
class AlarmMessageDefaultTypeInternal;
extern AlarmMessageDefaultTypeInternal _AlarmMessage_default_instance_;
namespace google {
namespace protobuf {
template<> ::AlarmMessage* Arena::CreateMaybeMessage<::AlarmMessage>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class AlarmMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:AlarmMessage) */ {
 public:
  AlarmMessage();
  virtual ~AlarmMessage();

  AlarmMessage(const AlarmMessage& from);

  inline AlarmMessage& operator=(const AlarmMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AlarmMessage(AlarmMessage&& from) noexcept
    : AlarmMessage() {
    *this = ::std::move(from);
  }

  inline AlarmMessage& operator=(AlarmMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AlarmMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AlarmMessage* internal_default_instance() {
    return reinterpret_cast<const AlarmMessage*>(
               &_AlarmMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(AlarmMessage* other);
  friend void swap(AlarmMessage& a, AlarmMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AlarmMessage* New() const final {
    return CreateMaybeMessage<AlarmMessage>(NULL);
  }

  AlarmMessage* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AlarmMessage>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AlarmMessage& from);
  void MergeFrom(const AlarmMessage& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AlarmMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool CtrolBoxHighTemAlarm = 1;
  void clear_ctrolboxhightemalarm();
  static const int kCtrolBoxHighTemAlarmFieldNumber = 1;
  bool ctrolboxhightemalarm() const;
  void set_ctrolboxhightemalarm(bool value);

  // bool CtrolBoxFrozenTemAlarm = 2;
  void clear_ctrolboxfrozentemalarm();
  static const int kCtrolBoxFrozenTemAlarmFieldNumber = 2;
  bool ctrolboxfrozentemalarm() const;
  void set_ctrolboxfrozentemalarm(bool value);

  // bool BMSModComLostAlarm = 3;
  void clear_bmsmodcomlostalarm();
  static const int kBMSModComLostAlarmFieldNumber = 3;
  bool bmsmodcomlostalarm() const;
  void set_bmsmodcomlostalarm(bool value);

  // bool Emergency_Status_stop = 4;
  void clear_emergency_status_stop();
  static const int kEmergencyStatusStopFieldNumber = 4;
  bool emergency_status_stop() const;
  void set_emergency_status_stop(bool value);

  // bool EcanExternSnsorNdeOFF = 5;
  void clear_ecanexternsnsorndeoff();
  static const int kEcanExternSnsorNdeOFFFieldNumber = 5;
  bool ecanexternsnsorndeoff() const;
  void set_ecanexternsnsorndeoff(bool value);

  // bool ZmqTransNodeOFF = 6;
  void clear_zmqtransnodeoff();
  static const int kZmqTransNodeOFFFieldNumber = 6;
  bool zmqtransnodeoff() const;
  void set_zmqtransnodeoff(bool value);

  // bool JoyTestNodeOFF = 7;
  void clear_joytestnodeoff();
  static const int kJoyTestNodeOFFFieldNumber = 7;
  bool joytestnodeoff() const;
  void set_joytestnodeoff(bool value);

  // @@protoc_insertion_point(class_scope:AlarmMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool ctrolboxhightemalarm_;
  bool ctrolboxfrozentemalarm_;
  bool bmsmodcomlostalarm_;
  bool emergency_status_stop_;
  bool ecanexternsnsorndeoff_;
  bool zmqtransnodeoff_;
  bool joytestnodeoff_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_AlarmMessage_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AlarmMessage

// bool CtrolBoxHighTemAlarm = 1;
inline void AlarmMessage::clear_ctrolboxhightemalarm() {
  ctrolboxhightemalarm_ = false;
}
inline bool AlarmMessage::ctrolboxhightemalarm() const {
  // @@protoc_insertion_point(field_get:AlarmMessage.CtrolBoxHighTemAlarm)
  return ctrolboxhightemalarm_;
}
inline void AlarmMessage::set_ctrolboxhightemalarm(bool value) {
  
  ctrolboxhightemalarm_ = value;
  // @@protoc_insertion_point(field_set:AlarmMessage.CtrolBoxHighTemAlarm)
}

// bool CtrolBoxFrozenTemAlarm = 2;
inline void AlarmMessage::clear_ctrolboxfrozentemalarm() {
  ctrolboxfrozentemalarm_ = false;
}
inline bool AlarmMessage::ctrolboxfrozentemalarm() const {
  // @@protoc_insertion_point(field_get:AlarmMessage.CtrolBoxFrozenTemAlarm)
  return ctrolboxfrozentemalarm_;
}
inline void AlarmMessage::set_ctrolboxfrozentemalarm(bool value) {
  
  ctrolboxfrozentemalarm_ = value;
  // @@protoc_insertion_point(field_set:AlarmMessage.CtrolBoxFrozenTemAlarm)
}

// bool BMSModComLostAlarm = 3;
inline void AlarmMessage::clear_bmsmodcomlostalarm() {
  bmsmodcomlostalarm_ = false;
}
inline bool AlarmMessage::bmsmodcomlostalarm() const {
  // @@protoc_insertion_point(field_get:AlarmMessage.BMSModComLostAlarm)
  return bmsmodcomlostalarm_;
}
inline void AlarmMessage::set_bmsmodcomlostalarm(bool value) {
  
  bmsmodcomlostalarm_ = value;
  // @@protoc_insertion_point(field_set:AlarmMessage.BMSModComLostAlarm)
}

// bool Emergency_Status_stop = 4;
inline void AlarmMessage::clear_emergency_status_stop() {
  emergency_status_stop_ = false;
}
inline bool AlarmMessage::emergency_status_stop() const {
  // @@protoc_insertion_point(field_get:AlarmMessage.Emergency_Status_stop)
  return emergency_status_stop_;
}
inline void AlarmMessage::set_emergency_status_stop(bool value) {
  
  emergency_status_stop_ = value;
  // @@protoc_insertion_point(field_set:AlarmMessage.Emergency_Status_stop)
}

// bool EcanExternSnsorNdeOFF = 5;
inline void AlarmMessage::clear_ecanexternsnsorndeoff() {
  ecanexternsnsorndeoff_ = false;
}
inline bool AlarmMessage::ecanexternsnsorndeoff() const {
  // @@protoc_insertion_point(field_get:AlarmMessage.EcanExternSnsorNdeOFF)
  return ecanexternsnsorndeoff_;
}
inline void AlarmMessage::set_ecanexternsnsorndeoff(bool value) {
  
  ecanexternsnsorndeoff_ = value;
  // @@protoc_insertion_point(field_set:AlarmMessage.EcanExternSnsorNdeOFF)
}

// bool ZmqTransNodeOFF = 6;
inline void AlarmMessage::clear_zmqtransnodeoff() {
  zmqtransnodeoff_ = false;
}
inline bool AlarmMessage::zmqtransnodeoff() const {
  // @@protoc_insertion_point(field_get:AlarmMessage.ZmqTransNodeOFF)
  return zmqtransnodeoff_;
}
inline void AlarmMessage::set_zmqtransnodeoff(bool value) {
  
  zmqtransnodeoff_ = value;
  // @@protoc_insertion_point(field_set:AlarmMessage.ZmqTransNodeOFF)
}

// bool JoyTestNodeOFF = 7;
inline void AlarmMessage::clear_joytestnodeoff() {
  joytestnodeoff_ = false;
}
inline bool AlarmMessage::joytestnodeoff() const {
  // @@protoc_insertion_point(field_get:AlarmMessage.JoyTestNodeOFF)
  return joytestnodeoff_;
}
inline void AlarmMessage::set_joytestnodeoff(bool value) {
  
  joytestnodeoff_ = value;
  // @@protoc_insertion_point(field_set:AlarmMessage.JoyTestNodeOFF)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_AlarmMessage_2eproto
