// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BmsModeConfig.proto

#ifndef PROTOBUF_INCLUDED_BmsModeConfig_2eproto
#define PROTOBUF_INCLUDED_BmsModeConfig_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_BmsModeConfig_2eproto 

namespace protobuf_BmsModeConfig_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_BmsModeConfig_2eproto
class BmsModeConfig;
class BmsModeConfigDefaultTypeInternal;
extern BmsModeConfigDefaultTypeInternal _BmsModeConfig_default_instance_;
class BmsModeConfig_Fan_Config;
class BmsModeConfig_Fan_ConfigDefaultTypeInternal;
extern BmsModeConfig_Fan_ConfigDefaultTypeInternal _BmsModeConfig_Fan_Config_default_instance_;
class BmsModeConfig_Nomal_Config;
class BmsModeConfig_Nomal_ConfigDefaultTypeInternal;
extern BmsModeConfig_Nomal_ConfigDefaultTypeInternal _BmsModeConfig_Nomal_Config_default_instance_;
class BmsModeConfig_SOC_Config;
class BmsModeConfig_SOC_ConfigDefaultTypeInternal;
extern BmsModeConfig_SOC_ConfigDefaultTypeInternal _BmsModeConfig_SOC_Config_default_instance_;
namespace google {
namespace protobuf {
template<> ::BmsModeConfig* Arena::CreateMaybeMessage<::BmsModeConfig>(Arena*);
template<> ::BmsModeConfig_Fan_Config* Arena::CreateMaybeMessage<::BmsModeConfig_Fan_Config>(Arena*);
template<> ::BmsModeConfig_Nomal_Config* Arena::CreateMaybeMessage<::BmsModeConfig_Nomal_Config>(Arena*);
template<> ::BmsModeConfig_SOC_Config* Arena::CreateMaybeMessage<::BmsModeConfig_SOC_Config>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class BmsModeConfig_SOC_Config : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BmsModeConfig.SOC_Config) */ {
 public:
  BmsModeConfig_SOC_Config();
  virtual ~BmsModeConfig_SOC_Config();

  BmsModeConfig_SOC_Config(const BmsModeConfig_SOC_Config& from);

  inline BmsModeConfig_SOC_Config& operator=(const BmsModeConfig_SOC_Config& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BmsModeConfig_SOC_Config(BmsModeConfig_SOC_Config&& from) noexcept
    : BmsModeConfig_SOC_Config() {
    *this = ::std::move(from);
  }

  inline BmsModeConfig_SOC_Config& operator=(BmsModeConfig_SOC_Config&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BmsModeConfig_SOC_Config& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BmsModeConfig_SOC_Config* internal_default_instance() {
    return reinterpret_cast<const BmsModeConfig_SOC_Config*>(
               &_BmsModeConfig_SOC_Config_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(BmsModeConfig_SOC_Config* other);
  friend void swap(BmsModeConfig_SOC_Config& a, BmsModeConfig_SOC_Config& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BmsModeConfig_SOC_Config* New() const final {
    return CreateMaybeMessage<BmsModeConfig_SOC_Config>(NULL);
  }

  BmsModeConfig_SOC_Config* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BmsModeConfig_SOC_Config>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BmsModeConfig_SOC_Config& from);
  void MergeFrom(const BmsModeConfig_SOC_Config& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BmsModeConfig_SOC_Config* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 Full_Soc = 1;
  void clear_full_soc();
  static const int kFullSocFieldNumber = 1;
  ::google::protobuf::int32 full_soc() const;
  void set_full_soc(::google::protobuf::int32 value);

  // int32 Current_Soc = 2;
  void clear_current_soc();
  static const int kCurrentSocFieldNumber = 2;
  ::google::protobuf::int32 current_soc() const;
  void set_current_soc(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:BmsModeConfig.SOC_Config)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 full_soc_;
  ::google::protobuf::int32 current_soc_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_BmsModeConfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BmsModeConfig_Fan_Config : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BmsModeConfig.Fan_Config) */ {
 public:
  BmsModeConfig_Fan_Config();
  virtual ~BmsModeConfig_Fan_Config();

  BmsModeConfig_Fan_Config(const BmsModeConfig_Fan_Config& from);

  inline BmsModeConfig_Fan_Config& operator=(const BmsModeConfig_Fan_Config& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BmsModeConfig_Fan_Config(BmsModeConfig_Fan_Config&& from) noexcept
    : BmsModeConfig_Fan_Config() {
    *this = ::std::move(from);
  }

  inline BmsModeConfig_Fan_Config& operator=(BmsModeConfig_Fan_Config&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BmsModeConfig_Fan_Config& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BmsModeConfig_Fan_Config* internal_default_instance() {
    return reinterpret_cast<const BmsModeConfig_Fan_Config*>(
               &_BmsModeConfig_Fan_Config_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(BmsModeConfig_Fan_Config* other);
  friend void swap(BmsModeConfig_Fan_Config& a, BmsModeConfig_Fan_Config& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BmsModeConfig_Fan_Config* New() const final {
    return CreateMaybeMessage<BmsModeConfig_Fan_Config>(NULL);
  }

  BmsModeConfig_Fan_Config* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BmsModeConfig_Fan_Config>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BmsModeConfig_Fan_Config& from);
  void MergeFrom(const BmsModeConfig_Fan_Config& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BmsModeConfig_Fan_Config* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 open = 1;
  void clear_open();
  static const int kOpenFieldNumber = 1;
  ::google::protobuf::int32 open() const;
  void set_open(::google::protobuf::int32 value);

  // int32 close = 2;
  void clear_close();
  static const int kCloseFieldNumber = 2;
  ::google::protobuf::int32 close() const;
  void set_close(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:BmsModeConfig.Fan_Config)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 open_;
  ::google::protobuf::int32 close_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_BmsModeConfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BmsModeConfig_Nomal_Config : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BmsModeConfig.Nomal_Config) */ {
 public:
  BmsModeConfig_Nomal_Config();
  virtual ~BmsModeConfig_Nomal_Config();

  BmsModeConfig_Nomal_Config(const BmsModeConfig_Nomal_Config& from);

  inline BmsModeConfig_Nomal_Config& operator=(const BmsModeConfig_Nomal_Config& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BmsModeConfig_Nomal_Config(BmsModeConfig_Nomal_Config&& from) noexcept
    : BmsModeConfig_Nomal_Config() {
    *this = ::std::move(from);
  }

  inline BmsModeConfig_Nomal_Config& operator=(BmsModeConfig_Nomal_Config&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BmsModeConfig_Nomal_Config& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BmsModeConfig_Nomal_Config* internal_default_instance() {
    return reinterpret_cast<const BmsModeConfig_Nomal_Config*>(
               &_BmsModeConfig_Nomal_Config_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(BmsModeConfig_Nomal_Config* other);
  friend void swap(BmsModeConfig_Nomal_Config& a, BmsModeConfig_Nomal_Config& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BmsModeConfig_Nomal_Config* New() const final {
    return CreateMaybeMessage<BmsModeConfig_Nomal_Config>(NULL);
  }

  BmsModeConfig_Nomal_Config* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BmsModeConfig_Nomal_Config>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BmsModeConfig_Nomal_Config& from);
  void MergeFrom(const BmsModeConfig_Nomal_Config& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BmsModeConfig_Nomal_Config* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 Ctrl_charge = 1;
  void clear_ctrl_charge();
  static const int kCtrlChargeFieldNumber = 1;
  ::google::protobuf::int32 ctrl_charge() const;
  void set_ctrl_charge(::google::protobuf::int32 value);

  // int32 Ctrl_fan = 2;
  void clear_ctrl_fan();
  static const int kCtrlFanFieldNumber = 2;
  ::google::protobuf::int32 ctrl_fan() const;
  void set_ctrl_fan(::google::protobuf::int32 value);

  // int32 Ctrl_reset = 3;
  void clear_ctrl_reset();
  static const int kCtrlResetFieldNumber = 3;
  ::google::protobuf::int32 ctrl_reset() const;
  void set_ctrl_reset(::google::protobuf::int32 value);

  // int32 Alarm_release = 4;
  void clear_alarm_release();
  static const int kAlarmReleaseFieldNumber = 4;
  ::google::protobuf::int32 alarm_release() const;
  void set_alarm_release(::google::protobuf::int32 value);

  // int32 Ctrl_motor_power = 5;
  void clear_ctrl_motor_power();
  static const int kCtrlMotorPowerFieldNumber = 5;
  ::google::protobuf::int32 ctrl_motor_power() const;
  void set_ctrl_motor_power(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:BmsModeConfig.Nomal_Config)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 ctrl_charge_;
  ::google::protobuf::int32 ctrl_fan_;
  ::google::protobuf::int32 ctrl_reset_;
  ::google::protobuf::int32 alarm_release_;
  ::google::protobuf::int32 ctrl_motor_power_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_BmsModeConfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BmsModeConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BmsModeConfig) */ {
 public:
  BmsModeConfig();
  virtual ~BmsModeConfig();

  BmsModeConfig(const BmsModeConfig& from);

  inline BmsModeConfig& operator=(const BmsModeConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BmsModeConfig(BmsModeConfig&& from) noexcept
    : BmsModeConfig() {
    *this = ::std::move(from);
  }

  inline BmsModeConfig& operator=(BmsModeConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BmsModeConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BmsModeConfig* internal_default_instance() {
    return reinterpret_cast<const BmsModeConfig*>(
               &_BmsModeConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(BmsModeConfig* other);
  friend void swap(BmsModeConfig& a, BmsModeConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BmsModeConfig* New() const final {
    return CreateMaybeMessage<BmsModeConfig>(NULL);
  }

  BmsModeConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BmsModeConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BmsModeConfig& from);
  void MergeFrom(const BmsModeConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BmsModeConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef BmsModeConfig_SOC_Config SOC_Config;
  typedef BmsModeConfig_Fan_Config Fan_Config;
  typedef BmsModeConfig_Nomal_Config Nomal_Config;

  // accessors -------------------------------------------------------

  // .BmsModeConfig.Nomal_Config Nomal = 1;
  bool has_nomal() const;
  void clear_nomal();
  static const int kNomalFieldNumber = 1;
  private:
  const ::BmsModeConfig_Nomal_Config& _internal_nomal() const;
  public:
  const ::BmsModeConfig_Nomal_Config& nomal() const;
  ::BmsModeConfig_Nomal_Config* release_nomal();
  ::BmsModeConfig_Nomal_Config* mutable_nomal();
  void set_allocated_nomal(::BmsModeConfig_Nomal_Config* nomal);

  // .BmsModeConfig.SOC_Config SOC = 2;
  bool has_soc() const;
  void clear_soc();
  static const int kSOCFieldNumber = 2;
  private:
  const ::BmsModeConfig_SOC_Config& _internal_soc() const;
  public:
  const ::BmsModeConfig_SOC_Config& soc() const;
  ::BmsModeConfig_SOC_Config* release_soc();
  ::BmsModeConfig_SOC_Config* mutable_soc();
  void set_allocated_soc(::BmsModeConfig_SOC_Config* soc);

  // .BmsModeConfig.Fan_Config fan = 3;
  bool has_fan() const;
  void clear_fan();
  static const int kFanFieldNumber = 3;
  private:
  const ::BmsModeConfig_Fan_Config& _internal_fan() const;
  public:
  const ::BmsModeConfig_Fan_Config& fan() const;
  ::BmsModeConfig_Fan_Config* release_fan();
  ::BmsModeConfig_Fan_Config* mutable_fan();
  void set_allocated_fan(::BmsModeConfig_Fan_Config* fan);

  // @@protoc_insertion_point(class_scope:BmsModeConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::BmsModeConfig_Nomal_Config* nomal_;
  ::BmsModeConfig_SOC_Config* soc_;
  ::BmsModeConfig_Fan_Config* fan_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_BmsModeConfig_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BmsModeConfig_SOC_Config

// int32 Full_Soc = 1;
inline void BmsModeConfig_SOC_Config::clear_full_soc() {
  full_soc_ = 0;
}
inline ::google::protobuf::int32 BmsModeConfig_SOC_Config::full_soc() const {
  // @@protoc_insertion_point(field_get:BmsModeConfig.SOC_Config.Full_Soc)
  return full_soc_;
}
inline void BmsModeConfig_SOC_Config::set_full_soc(::google::protobuf::int32 value) {
  
  full_soc_ = value;
  // @@protoc_insertion_point(field_set:BmsModeConfig.SOC_Config.Full_Soc)
}

// int32 Current_Soc = 2;
inline void BmsModeConfig_SOC_Config::clear_current_soc() {
  current_soc_ = 0;
}
inline ::google::protobuf::int32 BmsModeConfig_SOC_Config::current_soc() const {
  // @@protoc_insertion_point(field_get:BmsModeConfig.SOC_Config.Current_Soc)
  return current_soc_;
}
inline void BmsModeConfig_SOC_Config::set_current_soc(::google::protobuf::int32 value) {
  
  current_soc_ = value;
  // @@protoc_insertion_point(field_set:BmsModeConfig.SOC_Config.Current_Soc)
}

// -------------------------------------------------------------------

// BmsModeConfig_Fan_Config

// int32 open = 1;
inline void BmsModeConfig_Fan_Config::clear_open() {
  open_ = 0;
}
inline ::google::protobuf::int32 BmsModeConfig_Fan_Config::open() const {
  // @@protoc_insertion_point(field_get:BmsModeConfig.Fan_Config.open)
  return open_;
}
inline void BmsModeConfig_Fan_Config::set_open(::google::protobuf::int32 value) {
  
  open_ = value;
  // @@protoc_insertion_point(field_set:BmsModeConfig.Fan_Config.open)
}

// int32 close = 2;
inline void BmsModeConfig_Fan_Config::clear_close() {
  close_ = 0;
}
inline ::google::protobuf::int32 BmsModeConfig_Fan_Config::close() const {
  // @@protoc_insertion_point(field_get:BmsModeConfig.Fan_Config.close)
  return close_;
}
inline void BmsModeConfig_Fan_Config::set_close(::google::protobuf::int32 value) {
  
  close_ = value;
  // @@protoc_insertion_point(field_set:BmsModeConfig.Fan_Config.close)
}

// -------------------------------------------------------------------

// BmsModeConfig_Nomal_Config

// int32 Ctrl_charge = 1;
inline void BmsModeConfig_Nomal_Config::clear_ctrl_charge() {
  ctrl_charge_ = 0;
}
inline ::google::protobuf::int32 BmsModeConfig_Nomal_Config::ctrl_charge() const {
  // @@protoc_insertion_point(field_get:BmsModeConfig.Nomal_Config.Ctrl_charge)
  return ctrl_charge_;
}
inline void BmsModeConfig_Nomal_Config::set_ctrl_charge(::google::protobuf::int32 value) {
  
  ctrl_charge_ = value;
  // @@protoc_insertion_point(field_set:BmsModeConfig.Nomal_Config.Ctrl_charge)
}

// int32 Ctrl_fan = 2;
inline void BmsModeConfig_Nomal_Config::clear_ctrl_fan() {
  ctrl_fan_ = 0;
}
inline ::google::protobuf::int32 BmsModeConfig_Nomal_Config::ctrl_fan() const {
  // @@protoc_insertion_point(field_get:BmsModeConfig.Nomal_Config.Ctrl_fan)
  return ctrl_fan_;
}
inline void BmsModeConfig_Nomal_Config::set_ctrl_fan(::google::protobuf::int32 value) {
  
  ctrl_fan_ = value;
  // @@protoc_insertion_point(field_set:BmsModeConfig.Nomal_Config.Ctrl_fan)
}

// int32 Ctrl_reset = 3;
inline void BmsModeConfig_Nomal_Config::clear_ctrl_reset() {
  ctrl_reset_ = 0;
}
inline ::google::protobuf::int32 BmsModeConfig_Nomal_Config::ctrl_reset() const {
  // @@protoc_insertion_point(field_get:BmsModeConfig.Nomal_Config.Ctrl_reset)
  return ctrl_reset_;
}
inline void BmsModeConfig_Nomal_Config::set_ctrl_reset(::google::protobuf::int32 value) {
  
  ctrl_reset_ = value;
  // @@protoc_insertion_point(field_set:BmsModeConfig.Nomal_Config.Ctrl_reset)
}

// int32 Alarm_release = 4;
inline void BmsModeConfig_Nomal_Config::clear_alarm_release() {
  alarm_release_ = 0;
}
inline ::google::protobuf::int32 BmsModeConfig_Nomal_Config::alarm_release() const {
  // @@protoc_insertion_point(field_get:BmsModeConfig.Nomal_Config.Alarm_release)
  return alarm_release_;
}
inline void BmsModeConfig_Nomal_Config::set_alarm_release(::google::protobuf::int32 value) {
  
  alarm_release_ = value;
  // @@protoc_insertion_point(field_set:BmsModeConfig.Nomal_Config.Alarm_release)
}

// int32 Ctrl_motor_power = 5;
inline void BmsModeConfig_Nomal_Config::clear_ctrl_motor_power() {
  ctrl_motor_power_ = 0;
}
inline ::google::protobuf::int32 BmsModeConfig_Nomal_Config::ctrl_motor_power() const {
  // @@protoc_insertion_point(field_get:BmsModeConfig.Nomal_Config.Ctrl_motor_power)
  return ctrl_motor_power_;
}
inline void BmsModeConfig_Nomal_Config::set_ctrl_motor_power(::google::protobuf::int32 value) {
  
  ctrl_motor_power_ = value;
  // @@protoc_insertion_point(field_set:BmsModeConfig.Nomal_Config.Ctrl_motor_power)
}

// -------------------------------------------------------------------

// BmsModeConfig

// .BmsModeConfig.Nomal_Config Nomal = 1;
inline bool BmsModeConfig::has_nomal() const {
  return this != internal_default_instance() && nomal_ != NULL;
}
inline void BmsModeConfig::clear_nomal() {
  if (GetArenaNoVirtual() == NULL && nomal_ != NULL) {
    delete nomal_;
  }
  nomal_ = NULL;
}
inline const ::BmsModeConfig_Nomal_Config& BmsModeConfig::_internal_nomal() const {
  return *nomal_;
}
inline const ::BmsModeConfig_Nomal_Config& BmsModeConfig::nomal() const {
  const ::BmsModeConfig_Nomal_Config* p = nomal_;
  // @@protoc_insertion_point(field_get:BmsModeConfig.Nomal)
  return p != NULL ? *p : *reinterpret_cast<const ::BmsModeConfig_Nomal_Config*>(
      &::_BmsModeConfig_Nomal_Config_default_instance_);
}
inline ::BmsModeConfig_Nomal_Config* BmsModeConfig::release_nomal() {
  // @@protoc_insertion_point(field_release:BmsModeConfig.Nomal)
  
  ::BmsModeConfig_Nomal_Config* temp = nomal_;
  nomal_ = NULL;
  return temp;
}
inline ::BmsModeConfig_Nomal_Config* BmsModeConfig::mutable_nomal() {
  
  if (nomal_ == NULL) {
    auto* p = CreateMaybeMessage<::BmsModeConfig_Nomal_Config>(GetArenaNoVirtual());
    nomal_ = p;
  }
  // @@protoc_insertion_point(field_mutable:BmsModeConfig.Nomal)
  return nomal_;
}
inline void BmsModeConfig::set_allocated_nomal(::BmsModeConfig_Nomal_Config* nomal) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete nomal_;
  }
  if (nomal) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      nomal = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, nomal, submessage_arena);
    }
    
  } else {
    
  }
  nomal_ = nomal;
  // @@protoc_insertion_point(field_set_allocated:BmsModeConfig.Nomal)
}

// .BmsModeConfig.SOC_Config SOC = 2;
inline bool BmsModeConfig::has_soc() const {
  return this != internal_default_instance() && soc_ != NULL;
}
inline void BmsModeConfig::clear_soc() {
  if (GetArenaNoVirtual() == NULL && soc_ != NULL) {
    delete soc_;
  }
  soc_ = NULL;
}
inline const ::BmsModeConfig_SOC_Config& BmsModeConfig::_internal_soc() const {
  return *soc_;
}
inline const ::BmsModeConfig_SOC_Config& BmsModeConfig::soc() const {
  const ::BmsModeConfig_SOC_Config* p = soc_;
  // @@protoc_insertion_point(field_get:BmsModeConfig.SOC)
  return p != NULL ? *p : *reinterpret_cast<const ::BmsModeConfig_SOC_Config*>(
      &::_BmsModeConfig_SOC_Config_default_instance_);
}
inline ::BmsModeConfig_SOC_Config* BmsModeConfig::release_soc() {
  // @@protoc_insertion_point(field_release:BmsModeConfig.SOC)
  
  ::BmsModeConfig_SOC_Config* temp = soc_;
  soc_ = NULL;
  return temp;
}
inline ::BmsModeConfig_SOC_Config* BmsModeConfig::mutable_soc() {
  
  if (soc_ == NULL) {
    auto* p = CreateMaybeMessage<::BmsModeConfig_SOC_Config>(GetArenaNoVirtual());
    soc_ = p;
  }
  // @@protoc_insertion_point(field_mutable:BmsModeConfig.SOC)
  return soc_;
}
inline void BmsModeConfig::set_allocated_soc(::BmsModeConfig_SOC_Config* soc) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete soc_;
  }
  if (soc) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      soc = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, soc, submessage_arena);
    }
    
  } else {
    
  }
  soc_ = soc;
  // @@protoc_insertion_point(field_set_allocated:BmsModeConfig.SOC)
}

// .BmsModeConfig.Fan_Config fan = 3;
inline bool BmsModeConfig::has_fan() const {
  return this != internal_default_instance() && fan_ != NULL;
}
inline void BmsModeConfig::clear_fan() {
  if (GetArenaNoVirtual() == NULL && fan_ != NULL) {
    delete fan_;
  }
  fan_ = NULL;
}
inline const ::BmsModeConfig_Fan_Config& BmsModeConfig::_internal_fan() const {
  return *fan_;
}
inline const ::BmsModeConfig_Fan_Config& BmsModeConfig::fan() const {
  const ::BmsModeConfig_Fan_Config* p = fan_;
  // @@protoc_insertion_point(field_get:BmsModeConfig.fan)
  return p != NULL ? *p : *reinterpret_cast<const ::BmsModeConfig_Fan_Config*>(
      &::_BmsModeConfig_Fan_Config_default_instance_);
}
inline ::BmsModeConfig_Fan_Config* BmsModeConfig::release_fan() {
  // @@protoc_insertion_point(field_release:BmsModeConfig.fan)
  
  ::BmsModeConfig_Fan_Config* temp = fan_;
  fan_ = NULL;
  return temp;
}
inline ::BmsModeConfig_Fan_Config* BmsModeConfig::mutable_fan() {
  
  if (fan_ == NULL) {
    auto* p = CreateMaybeMessage<::BmsModeConfig_Fan_Config>(GetArenaNoVirtual());
    fan_ = p;
  }
  // @@protoc_insertion_point(field_mutable:BmsModeConfig.fan)
  return fan_;
}
inline void BmsModeConfig::set_allocated_fan(::BmsModeConfig_Fan_Config* fan) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete fan_;
  }
  if (fan) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      fan = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, fan, submessage_arena);
    }
    
  } else {
    
  }
  fan_ = fan;
  // @@protoc_insertion_point(field_set_allocated:BmsModeConfig.fan)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_BmsModeConfig_2eproto
