// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AlarmMessage.proto

#include "AlarmMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

class AlarmMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<AlarmMessage>
      _instance;
} _AlarmMessage_default_instance_;
namespace protobuf_AlarmMessage_2eproto {
static void InitDefaultsAlarmMessage() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_AlarmMessage_default_instance_;
    new (ptr) ::AlarmMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::AlarmMessage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_AlarmMessage =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsAlarmMessage}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_AlarmMessage.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AlarmMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AlarmMessage, ctrolboxhightemalarm_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AlarmMessage, ctrolboxfrozentemalarm_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AlarmMessage, bmsmodcomlostalarm_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AlarmMessage, emergency_status_stop_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AlarmMessage, ecanexternsnsorndeoff_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AlarmMessage, zmqtransnodeoff_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AlarmMessage, joytestnodeoff_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::AlarmMessage)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_AlarmMessage_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "AlarmMessage.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\022AlarmMessage.proto\"\327\001\n\014AlarmMessage\022\034\n"
      "\024CtrolBoxHighTemAlarm\030\001 \001(\010\022\036\n\026CtrolBoxF"
      "rozenTemAlarm\030\002 \001(\010\022\032\n\022BMSModComLostAlar"
      "m\030\003 \001(\010\022\035\n\025Emergency_Status_stop\030\004 \001(\010\022\035"
      "\n\025EcanExternSnsorNdeOFF\030\005 \001(\010\022\027\n\017ZmqTran"
      "sNodeOFF\030\006 \001(\010\022\026\n\016JoyTestNodeOFF\030\007 \001(\010b\006"
      "proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 246);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "AlarmMessage.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_AlarmMessage_2eproto

// ===================================================================

void AlarmMessage::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AlarmMessage::kCtrolBoxHighTemAlarmFieldNumber;
const int AlarmMessage::kCtrolBoxFrozenTemAlarmFieldNumber;
const int AlarmMessage::kBMSModComLostAlarmFieldNumber;
const int AlarmMessage::kEmergencyStatusStopFieldNumber;
const int AlarmMessage::kEcanExternSnsorNdeOFFFieldNumber;
const int AlarmMessage::kZmqTransNodeOFFFieldNumber;
const int AlarmMessage::kJoyTestNodeOFFFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AlarmMessage::AlarmMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_AlarmMessage_2eproto::scc_info_AlarmMessage.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:AlarmMessage)
}
AlarmMessage::AlarmMessage(const AlarmMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&ctrolboxhightemalarm_, &from.ctrolboxhightemalarm_,
    static_cast<size_t>(reinterpret_cast<char*>(&joytestnodeoff_) -
    reinterpret_cast<char*>(&ctrolboxhightemalarm_)) + sizeof(joytestnodeoff_));
  // @@protoc_insertion_point(copy_constructor:AlarmMessage)
}

void AlarmMessage::SharedCtor() {
  ::memset(&ctrolboxhightemalarm_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&joytestnodeoff_) -
      reinterpret_cast<char*>(&ctrolboxhightemalarm_)) + sizeof(joytestnodeoff_));
}

AlarmMessage::~AlarmMessage() {
  // @@protoc_insertion_point(destructor:AlarmMessage)
  SharedDtor();
}

void AlarmMessage::SharedDtor() {
}

void AlarmMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* AlarmMessage::descriptor() {
  ::protobuf_AlarmMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_AlarmMessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const AlarmMessage& AlarmMessage::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_AlarmMessage_2eproto::scc_info_AlarmMessage.base);
  return *internal_default_instance();
}


void AlarmMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:AlarmMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&ctrolboxhightemalarm_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&joytestnodeoff_) -
      reinterpret_cast<char*>(&ctrolboxhightemalarm_)) + sizeof(joytestnodeoff_));
  _internal_metadata_.Clear();
}

bool AlarmMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:AlarmMessage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool CtrolBoxHighTemAlarm = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &ctrolboxhightemalarm_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool CtrolBoxFrozenTemAlarm = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &ctrolboxfrozentemalarm_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool BMSModComLostAlarm = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &bmsmodcomlostalarm_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool Emergency_Status_stop = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &emergency_status_stop_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool EcanExternSnsorNdeOFF = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &ecanexternsnsorndeoff_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool ZmqTransNodeOFF = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &zmqtransnodeoff_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool JoyTestNodeOFF = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &joytestnodeoff_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:AlarmMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:AlarmMessage)
  return false;
#undef DO_
}

void AlarmMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:AlarmMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool CtrolBoxHighTemAlarm = 1;
  if (this->ctrolboxhightemalarm() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->ctrolboxhightemalarm(), output);
  }

  // bool CtrolBoxFrozenTemAlarm = 2;
  if (this->ctrolboxfrozentemalarm() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->ctrolboxfrozentemalarm(), output);
  }

  // bool BMSModComLostAlarm = 3;
  if (this->bmsmodcomlostalarm() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->bmsmodcomlostalarm(), output);
  }

  // bool Emergency_Status_stop = 4;
  if (this->emergency_status_stop() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->emergency_status_stop(), output);
  }

  // bool EcanExternSnsorNdeOFF = 5;
  if (this->ecanexternsnsorndeoff() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->ecanexternsnsorndeoff(), output);
  }

  // bool ZmqTransNodeOFF = 6;
  if (this->zmqtransnodeoff() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(6, this->zmqtransnodeoff(), output);
  }

  // bool JoyTestNodeOFF = 7;
  if (this->joytestnodeoff() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(7, this->joytestnodeoff(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:AlarmMessage)
}

::google::protobuf::uint8* AlarmMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:AlarmMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool CtrolBoxHighTemAlarm = 1;
  if (this->ctrolboxhightemalarm() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->ctrolboxhightemalarm(), target);
  }

  // bool CtrolBoxFrozenTemAlarm = 2;
  if (this->ctrolboxfrozentemalarm() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->ctrolboxfrozentemalarm(), target);
  }

  // bool BMSModComLostAlarm = 3;
  if (this->bmsmodcomlostalarm() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->bmsmodcomlostalarm(), target);
  }

  // bool Emergency_Status_stop = 4;
  if (this->emergency_status_stop() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->emergency_status_stop(), target);
  }

  // bool EcanExternSnsorNdeOFF = 5;
  if (this->ecanexternsnsorndeoff() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->ecanexternsnsorndeoff(), target);
  }

  // bool ZmqTransNodeOFF = 6;
  if (this->zmqtransnodeoff() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(6, this->zmqtransnodeoff(), target);
  }

  // bool JoyTestNodeOFF = 7;
  if (this->joytestnodeoff() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(7, this->joytestnodeoff(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AlarmMessage)
  return target;
}

size_t AlarmMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:AlarmMessage)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bool CtrolBoxHighTemAlarm = 1;
  if (this->ctrolboxhightemalarm() != 0) {
    total_size += 1 + 1;
  }

  // bool CtrolBoxFrozenTemAlarm = 2;
  if (this->ctrolboxfrozentemalarm() != 0) {
    total_size += 1 + 1;
  }

  // bool BMSModComLostAlarm = 3;
  if (this->bmsmodcomlostalarm() != 0) {
    total_size += 1 + 1;
  }

  // bool Emergency_Status_stop = 4;
  if (this->emergency_status_stop() != 0) {
    total_size += 1 + 1;
  }

  // bool EcanExternSnsorNdeOFF = 5;
  if (this->ecanexternsnsorndeoff() != 0) {
    total_size += 1 + 1;
  }

  // bool ZmqTransNodeOFF = 6;
  if (this->zmqtransnodeoff() != 0) {
    total_size += 1 + 1;
  }

  // bool JoyTestNodeOFF = 7;
  if (this->joytestnodeoff() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AlarmMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:AlarmMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const AlarmMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const AlarmMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:AlarmMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:AlarmMessage)
    MergeFrom(*source);
  }
}

void AlarmMessage::MergeFrom(const AlarmMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:AlarmMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.ctrolboxhightemalarm() != 0) {
    set_ctrolboxhightemalarm(from.ctrolboxhightemalarm());
  }
  if (from.ctrolboxfrozentemalarm() != 0) {
    set_ctrolboxfrozentemalarm(from.ctrolboxfrozentemalarm());
  }
  if (from.bmsmodcomlostalarm() != 0) {
    set_bmsmodcomlostalarm(from.bmsmodcomlostalarm());
  }
  if (from.emergency_status_stop() != 0) {
    set_emergency_status_stop(from.emergency_status_stop());
  }
  if (from.ecanexternsnsorndeoff() != 0) {
    set_ecanexternsnsorndeoff(from.ecanexternsnsorndeoff());
  }
  if (from.zmqtransnodeoff() != 0) {
    set_zmqtransnodeoff(from.zmqtransnodeoff());
  }
  if (from.joytestnodeoff() != 0) {
    set_joytestnodeoff(from.joytestnodeoff());
  }
}

void AlarmMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:AlarmMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AlarmMessage::CopyFrom(const AlarmMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AlarmMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AlarmMessage::IsInitialized() const {
  return true;
}

void AlarmMessage::Swap(AlarmMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AlarmMessage::InternalSwap(AlarmMessage* other) {
  using std::swap;
  swap(ctrolboxhightemalarm_, other->ctrolboxhightemalarm_);
  swap(ctrolboxfrozentemalarm_, other->ctrolboxfrozentemalarm_);
  swap(bmsmodcomlostalarm_, other->bmsmodcomlostalarm_);
  swap(emergency_status_stop_, other->emergency_status_stop_);
  swap(ecanexternsnsorndeoff_, other->ecanexternsnsorndeoff_);
  swap(zmqtransnodeoff_, other->zmqtransnodeoff_);
  swap(joytestnodeoff_, other->joytestnodeoff_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata AlarmMessage::GetMetadata() const {
  protobuf_AlarmMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_AlarmMessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::AlarmMessage* Arena::CreateMaybeMessage< ::AlarmMessage >(Arena* arena) {
  return Arena::CreateInternal< ::AlarmMessage >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
